"""make created_at columns timezone-aware

Revision ID: 8a6822d42a4b
Revises: 0fba3db9e9c3
Create Date: 2026-09-12 04:04:41.749985

Note: hand-written, not autogenerated. SQLite (used for local dev/test
autogenerate diffing) doesn't distinguish timezone-aware from naive
DateTime columns, so `alembic revision --autogenerate` produced an empty
diff here even though the actual bug (asyncpg rejecting a tz-aware Python
datetime against a `TIMESTAMP WITHOUT TIME ZONE` column) is very real on
Postgres. The `postgresql_using` clause is required because Postgres
can't implicitly cast WITHOUT TIME ZONE -> WITH TIME ZONE; we tell it to
assume existing naive values were already UTC.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '8a6822d42a4b'
down_revision: Union[str, Sequence[str], None] = '0fba3db9e9c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

TABLES_AND_COLUMN = [
    ("users", "created_at"),
    ("products", "created_at"),
    ("orders", "created_at"),
]


def upgrade() -> None:
    for table, column in TABLES_AND_COLUMN:
        op.alter_column(
            table,
            column,
            type_=sa.DateTime(timezone=True),
            existing_type=sa.DateTime(timezone=False),
            postgresql_using=f"{column} AT TIME ZONE 'UTC'",
        )


def downgrade() -> None:
    for table, column in TABLES_AND_COLUMN:
        op.alter_column(
            table,
            column,
            type_=sa.DateTime(timezone=False),
            existing_type=sa.DateTime(timezone=True),
        )
